import { randomUUID } from "node:crypto";
import { mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { detectCommunities } from "@/community/leiden";
import { buildSummaryTree, getOrCreateLevel1Summary } from "@/community/raptor";
import { summarizeCommunities } from "@/community/summarize";
import type { SiaDb } from "@/graph/db-interface";
import { insertEdge } from "@/graph/edges";
import { insertEntity } from "@/graph/entities";
import { openGraphDb } from "@/graph/semantic-db";

async function seedGraph(db: SiaDb) {
	const ids: string[] = [];
	for (let i = 0; i < 4; i++) {
		const entity = await insertEntity(db, {
			type: "Function",
			name: `entity-${i}`,
			content: `content-${i}`,
			summary: `summary-${i}`,
		});
		ids.push(entity.id);
	}
	for (let i = 0; i < ids.length - 1; i++) {
		await insertEdge(db, { from_id: ids[i], to_id: ids[i + 1], type: "calls", weight: 1 });
	}
	return ids;
}

describe("buildSummaryTree", () => {
	let tmpDir: string;
	let db: SiaDb | undefined;

	function makeTmp(): string {
		const dir = join(tmpdir(), `sia-test-${randomUUID()}`);
		mkdirSync(dir, { recursive: true });
		return dir;
	}

	afterEach(async () => {
		if (db) {
			await db.close();
			db = undefined;
		}
		if (tmpDir) rmSync(tmpDir, { recursive: true, force: true });
	});

	it("populates Level 0, 2, 3 eagerly; Level 1 is lazy", async () => {
		tmpDir = makeTmp();
		db = openGraphDb("raptor-repo", tmpDir);
		const ids = await seedGraph(db);

		await detectCommunities(db);
		await summarizeCommunities(db, { airGapped: false });
		await buildSummaryTree(db);

		const counts = await db.execute(
			"SELECT level, COUNT(*) as count FROM summary_tree GROUP BY level ORDER BY level",
		);
		const countMap = new Map<number, number>(
			(counts.rows as Array<{ level: number; count: number }>).map((r) => [r.level, r.count]),
		);
		expect(countMap.get(0)).toBe(ids.length);
		// Level 1 is now lazy — not generated by buildSummaryTree
		expect(countMap.get(1) ?? 0).toBe(0);
		expect((countMap.get(2) ?? 0) > 0).toBe(true);
		expect((countMap.get(3) ?? 0) > 0).toBe(true);

		// Lazy Level 1: generate on demand via getOrCreateLevel1Summary
		const summary = await getOrCreateLevel1Summary(db, ids[0]);
		expect(summary).not.toBeNull();
		const lvl1Row = await db.execute("SELECT * FROM summary_tree WHERE id = ?", [`lvl1:${ids[0]}`]);
		expect(lvl1Row.rows.length).toBe(1);

		// Invalidated entity: Level 1 should have expires_at set
		await db.execute("UPDATE entities SET t_valid_until = ? WHERE id = ?", [Date.now(), ids[1]]);
		const expiredSummary = await getOrCreateLevel1Summary(db, ids[1]);
		expect(expiredSummary).not.toBeNull();
		const expired = await db.execute("SELECT expires_at FROM summary_tree WHERE id = ?", [
			`lvl1:${ids[1]}`,
		]);
		expect((expired.rows[0] as { expires_at: number | null }).expires_at).not.toBeNull();
	});
});
