// Module: export-knowledge — Generate human-readable knowledge document
//
// Queries the graph and produces a structured markdown document organized
// by knowledge category: decisions, conventions, bugs, solutions, concepts,
// community structure, and documentation.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { SiaDb } from "@/graph/db-interface";

export interface ExportOptions {
	projectName?: string;
	outputPath?: string;
	includeCommunities?: boolean;
	includeCodeEntities?: boolean;
}

interface EntityRow {
	id: string;
	type: string;
	name: string;
	content: string;
	summary: string | null;
	trust_tier: number;
	importance: number;
	created_at: number;
	file_paths: string | null;
	kind: string | null;
}

async function queryByType(db: SiaDb, type: string, limit: number = 50): Promise<EntityRow[]> {
	const result = await db.execute(
		`SELECT id, type, name, content, summary, trust_tier, importance, created_at, file_paths, kind
		 FROM graph_nodes
		 WHERE type = ? AND t_valid_until IS NULL AND archived_at IS NULL
		 ORDER BY importance DESC, created_at DESC
		 LIMIT ?`,
		[type, limit],
	);
	return result.rows as unknown as EntityRow[];
}

function formatDate(ms: number): string {
	return new Date(ms).toISOString().split("T")[0];
}

function tierLabel(tier: number): string {
	return tier === 1 ? "verified" : tier === 2 ? "code-derived" : tier === 3 ? "inferred" : "external";
}

function formatEntities(entities: EntityRow[], showContent: boolean = true): string {
	if (entities.length === 0) return "*None captured yet.*\n";

	return entities.map((e) => {
		const date = formatDate(e.created_at);
		const tier = tierLabel(e.trust_tier);
		const files = e.file_paths ? ` | Files: ${e.file_paths}` : "";
		let text = `### ${e.name}\n`;
		text += `*${date} | ${tier}${files}*\n\n`;
		if (showContent && e.content) {
			text += `${e.content.slice(0, 500)}\n`;
		} else if (e.summary) {
			text += `${e.summary}\n`;
		}
		return text;
	}).join("\n---\n\n");
}

export async function generateKnowledgeDocument(
	db: SiaDb,
	opts: ExportOptions = {},
): Promise<string> {
	const projectName = opts.projectName ?? "Project";

	const decisions = await queryByType(db, "Decision");
	const conventions = await queryByType(db, "Convention");
	const bugs = await queryByType(db, "Bug");
	const solutions = await queryByType(db, "Solution");
	const concepts = await queryByType(db, "Concept");

	// Count totals
	const totalResult = await db.execute(
		"SELECT COUNT(*) as cnt FROM graph_nodes WHERE t_valid_until IS NULL AND archived_at IS NULL",
	);
	const totalEntities = (totalResult.rows[0] as any).cnt;

	if (totalEntities === 0) {
		return `# ${projectName} — Knowledge Base\n\n*No knowledge captured yet. Run \`/sia-learn\` to build the knowledge graph.*\n`;
	}

	const sections: string[] = [];

	// Header
	sections.push(`# ${projectName} — Knowledge Base`);
	sections.push(`\n*Generated by SIA on ${formatDate(Date.now())} | ${totalEntities} total entities*\n`);
	sections.push("---\n");

	// Table of Contents
	sections.push("## Table of Contents\n");
	if (decisions.length > 0) sections.push(`- [Architectural Decisions](#architectural-decisions) (${decisions.length})`);
	if (conventions.length > 0) sections.push(`- [Coding Conventions](#coding-conventions) (${conventions.length})`);
	if (bugs.length > 0) sections.push(`- [Known Issues](#known-issues) (${bugs.length})`);
	if (solutions.length > 0) sections.push(`- [Solutions](#solutions) (${solutions.length})`);
	if (concepts.length > 0) sections.push(`- [Key Concepts](#key-concepts) (${concepts.length})`);
	sections.push("");

	// Decisions
	if (decisions.length > 0) {
		sections.push("## Architectural Decisions\n");
		sections.push(formatEntities(decisions));
	}

	// Conventions
	if (conventions.length > 0) {
		sections.push("## Coding Conventions\n");
		sections.push(formatEntities(conventions));
	}

	// Bugs
	if (bugs.length > 0) {
		sections.push("## Known Issues\n");
		sections.push(formatEntities(bugs));
	}

	// Solutions
	if (solutions.length > 0) {
		sections.push("## Solutions\n");
		sections.push(formatEntities(solutions));
	}

	// Concepts
	if (concepts.length > 0) {
		sections.push("## Key Concepts\n");
		sections.push(formatEntities(concepts));
	}

	// Community structure
	if (opts.includeCommunities !== false) {
		const communities = await db.execute(
			"SELECT id, summary, member_count FROM communities WHERE level = 2 ORDER BY member_count DESC LIMIT 10",
		);
		if ((communities.rows as any[]).length > 0) {
			sections.push("## Architecture (Community Structure)\n");
			for (const c of communities.rows as any[]) {
				sections.push(`### Community (${c.member_count} members)`);
				sections.push(`${c.summary ?? "No summary available"}\n`);
			}
		}
	}

	// Footer
	sections.push("---\n");
	sections.push("*This document was auto-generated by SIA's knowledge graph export.*");
	sections.push("*Run `/sia-export-knowledge` to regenerate with the latest knowledge.*");

	return sections.join("\n");
}

export async function runExportKnowledge(args: string[]): Promise<void> {
	const { resolveRepoHash } = await import("@/capture/hook");
	const { openGraphDb } = await import("@/graph/semantic-db");
	const { resolveSiaHome } = await import("@/shared/config");

	let outputPath = "KNOWLEDGE.md";
	let projectName: string | undefined;

	for (let i = 0; i < args.length; i++) {
		if (args[i] === "--output" && args[i + 1]) outputPath = args[++i];
		if (args[i] === "--name" && args[i + 1]) projectName = args[++i];
	}

	const cwd = process.cwd();
	const repoHash = resolveRepoHash(cwd);
	const siaHome = resolveSiaHome();
	const db = openGraphDb(repoHash, siaHome);

	try {
		// Auto-detect project name from package.json if not provided
		if (!projectName) {
			try {
				const { readFileSync } = await import("node:fs");
				const pkg = JSON.parse(readFileSync(join(cwd, "package.json"), "utf-8"));
				projectName = pkg.name;
			} catch {
				projectName = cwd.split("/").pop() ?? "Project";
			}
		}

		const markdown = await generateKnowledgeDocument(db, { projectName });
		const fullPath = join(cwd, outputPath);
		writeFileSync(fullPath, markdown, "utf-8");
		console.log(`Knowledge document written to ${outputPath} (${markdown.length} chars)`);
	} finally {
		await db.close();
	}
}
